@id("4f173486-2313-4694-a9ad-68c2cdc5324b")
@nodeType("705")
SELECT
     `O_ORDERKEY` AS `O_ORDERKEY`,
     `O_CUSTKEY` AS `O_CUSTKEY`,
     `O_ORDERSTATUS` AS `O_ORDERSTATUS`,
     `O_TOTALPRICE` AS `O_TOTALPRICE`,
     `O_ORDERDATE` AS `O_ORDERDATE`,
     `O_ORDERPRIORITY` AS `O_ORDERPRIORITY`,
     `O_CLERK` AS `O_CLERK`,
     `O_SHIPPRIORITY` AS `O_SHIPPRIORITY`,
     `O_COMMENT` AS `O_COMMENT`
FROM {{ ref('SRC', 'orders') }} `orders`