@id(`555bbc12-e672-4010-a9f3-93cdcdc61039`)
@nodeType("705")
@description("Table desc")
SELECT
     `N_NATIONKEY` AS `N_NATIONKEY`,
     `N_NAME` AS `N_NAME`,
     `N_REGIONKEY` AS `N_REGIONKEY`,
     `N_COMMENT` AS `N_COMMENT`,
     `last_modified` AS `last_modified` @foreign,
     `last_modified` AS `FR_DEFAULT_UNIT` @freshness(1),
     `last_modified` AS `FR_SECOND` @freshness(1, `SECOND`),
     `last_modified` AS `FR_MINUTE` @freshness(1, `MINUTE`),
     `last_modified` AS `FR_HOUR` @freshness(1, `HOUR`),
     `last_modified` AS `FR_DAY` @freshness(1, `DAY`),
     `last_modified` AS `FR_WEEK` @freshness(1, `WEEK`),
     `last_modified` AS `FR_MONTH` @freshness(1, `MONTH`),
     `last_modified` AS `FR_YEAR` @freshness(1, `YEAR`),
     `last_modified` AS `FR_LARGE_INTERVAL` @freshness(100, `YEAR`),
     `last_modified` AS `FR_ZERO_INTERVAL` @freshness(0, `SECOND`),

     CAST(`last_modified` AS DATE) AS `DT_DATE`,
     CAST(`last_modified` AS DATE) AS `DT_DATE_FR_DEFAULT_UNIT` @freshness(1),
     CAST(`last_modified` AS DATE) AS `DT_DATE_FR_SECOND` @freshness(1, `SECOND`),
     CAST(`last_modified` AS DATE) AS `DT_DATE_FR_MINUTE` @freshness(1, `MINUTE`),
     CAST(`last_modified` AS DATE) AS `DT_DATE_FR_HOUR` @freshness(1, `HOUR`),
     CAST(`last_modified` AS DATE) AS `DT_DATE_FR_DAY` @freshness(1, `DAY`),
     CAST(`last_modified` AS DATE) AS `DT_DATE_FR_WEEK` @freshness(1, `WEEK`),
     CAST(`last_modified` AS DATE) AS `DT_DATE_FR_MONTH` @freshness(1, `MONTH`),
     CAST(`last_modified` AS DATE) AS `DT_DATE_FR_YEAR` @freshness(1, `YEAR`),
     CAST(`last_modified` AS DATE) AS `DT_DATE_FR_LARGE_INTERVAL` @freshness(100, `YEAR`),
     CAST(`last_modified` AS DATE) AS `DT_DATE_FR_ZERO_INTERVAL` @freshness(0, `SECOND`),

     CAST(`last_modified` AS DATETIME) AS `DT_DATETIME`,
     CAST(`last_modified` AS DATETIME) AS `DT_DATETIME_FR_DEFAULT_UNIT` @freshness(1),
     CAST(`last_modified` AS DATETIME) AS `DT_DATETIME_FR_SECOND` @freshness(1, `SECOND`),
     CAST(`last_modified` AS DATETIME) AS `DT_DATETIME_FR_MINUTE` @freshness(1, `MINUTE`),
     CAST(`last_modified` AS DATETIME) AS `DT_DATETIME_FR_HOUR` @freshness(1, `HOUR`),
     CAST(`last_modified` AS DATETIME) AS `DT_DATETIME_FR_DAY` @freshness(1, `DAY`),
     CAST(`last_modified` AS DATETIME) AS `DT_DATETIME_FR_WEEK` @freshness(1, `WEEK`),
     CAST(`last_modified` AS DATETIME) AS `DT_DATETIME_FR_MONTH` @freshness(1, `MONTH`),
     CAST(`last_modified` AS DATETIME) AS `DT_DATETIME_FR_YEAR` @freshness(1, `YEAR`),
     CAST(`last_modified` AS DATETIME) AS `DT_DATETIME_FR_LARGE_INTERVAL` @freshness(100, `YEAR`),
     CAST(`last_modified` AS DATETIME) AS `DT_DATETIME_FR_ZERO_INTERVAL` @freshness(0, `SECOND`),

     CAST(`last_modified` AS TIMESTAMP) AS `DT_TIMESTAMP`,
     CAST(`last_modified` AS TIMESTAMP) AS `DT_TIMESTAMP_FR_DEFAULT_UNIT` @freshness(1),
     CAST(`last_modified` AS TIMESTAMP) AS `DT_TIMESTAMP_FR_SECOND` @freshness(1, `SECOND`),
     CAST(`last_modified` AS TIMESTAMP) AS `DT_TIMESTAMP_FR_MINUTE` @freshness(1, `MINUTE`),
     CAST(`last_modified` AS TIMESTAMP) AS `DT_TIMESTAMP_FR_HOUR` @freshness(1, `HOUR`),
     CAST(`last_modified` AS TIMESTAMP) AS `DT_TIMESTAMP_FR_DAY` @freshness(1, `DAY`),
     CAST(`last_modified` AS TIMESTAMP) AS `DT_TIMESTAMP_FR_WEEK` @freshness(1, `WEEK`),
     CAST(`last_modified` AS TIMESTAMP) AS `DT_TIMESTAMP_FR_MONTH` @freshness(1, `MONTH`),
     CAST(`last_modified` AS TIMESTAMP) AS `DT_TIMESTAMP_FR_YEAR` @freshness(1, `YEAR`),
     CAST(`last_modified` AS TIMESTAMP) AS `DT_TIMESTAMP_FR_LARGE_INTERVAL` @freshness(100, `YEAR`),
     CAST(`last_modified` AS TIMESTAMP) AS `DT_TIMESTAMP_FR_ZERO_INTERVAL` @freshness(0, `SECOND`)
FROM {{ ref('SRC', 'nation') }} `nation`